# Generated by Django 3.0 on 2019-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='articles')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='home',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
