# Generated by Django 3.0 on 2019-12-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191213_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='backend.Job'),
        ),
    ]
