# Generated by Django 3.0 on 2019-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20191214_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
